name: cassava_healthy_finder
description: A Cassava Healthy Finder app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: 14.9.4
  firebase_storage: 11.7.7
  flutter:
    sdk: flutter
  flutter_iconpicker: ^4.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.0.5
  share_plus: 9.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/assets/onboarding1.png
    - assets/assets/onboarding2.png
    - assets/assets/onboarding3.png
    - assets/assets/background.jpg
    - assets/assets/privacy.png
    - assets/assets/upload_icon.png
    - assets/assets/leaf_example.jpg
    - assets/assets/cultivation_tips.png
    - assets/assets/onboarding3.png
    - assets/assets/user_02.png
    - assets/assets/onboarding4.png
    - assets/assets/onboarding11.png
